# Generated by Django 3.0.3 on 2020-02-19 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(help_text='Enter a name', max_length=50)),
                ('code', models.CharField(help_text='Enter a code', max_length=50)),
                ('discription', models.TextField(blank=True, help_text='Enter a brief description of the course', max_length=1000, null=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['coursename'],
            },
        ),
        migrations.CreateModel(
            name='Navibar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a menu genre (e.g. Home, About Us)', max_length=50)),
                ('sort', models.IntegerField()),
                ('lang', models.BooleanField(choices=[(0, 'VN'), (1, 'USA')], default='0', help_text='Language availability')),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Enter a description of the major', null=True)),
                ('summary', models.TextField(blank=True, help_text='Enter a brief description of the book', max_length=1000, null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('visibility', models.BooleanField(choices=[(0, 'Hide'), (1, 'Visible')], default='1', help_text='Post availability')),
                ('navibar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.Navibar')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
